obj-$(CONFIG_AUTOSMP) += autosmp.o
obj-$(CONFIG_ZEN_DECISION) += msm_zen_decision.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_BRICKED_HOTPLUG)   += bricked_hotplug.o
obj-$(CONFIG_MSM_SLEEPER) += msm-sleeper.o
